### ISSUE TITLE
Support for Generating Images

### ISSUE THREAD

**Issue by abhillman** [bufbuild/rules_buf#18]
It could be useful to have a rule for generating images; e.g.

```
bazel build //protos:create_image > myrepo/protos/image.json
```

When using bazel, it can be nice to have it manage binary deps (i.e. as opposed to having to install various tools on dev boxes).

**Comment by srikrsna-buf** [comment]
[rules_proto](https://github.com/bazelbuild/rules_proto) provides `proto_descriptor_set` rule that outputs a `FileDescriptorSet` which is compatible with [Images](https://docs.buf.build/reference/images#what-are-buf-images). 

Here's an example:

```starlark
load("@rules_proto//proto:defs.bzl", "proto_descriptor_set")

proto_descriptor_set(
    name = "foo_proto_desc",
    # `proto_library` targets
    deps = [
        ":foo_proto",
        ":bar_proto",
    ],
)
```

I'm closing this issue, happy to answer any follow up questions.
