### ISSUE TITLE
Print violated lint rule name

### ISSUE THREAD

**Issue by aryeh-looker** [bufbuild/rules_buf#19]
When a lint rule is violated, it can be time consuming to figure out its corresponding name at https://docs.buf.build/lint/rules. It would be helpful if the rule name were printed (e.g. if a team wants to disable).

**Comment by srikrsna-buf** [comment]
Hi @aryeh-looker 

Thank you for the feedback, there is actually a way to print the lint configuration needed to silent the errors when running `buf lint` using the `--error-format` [flag](https://docs.buf.build/lint/usage#copy). We should add that to Bazel rules as well. Expect a PR soon.
