### ISSUE TITLE
buf_lint_test appears not to respect config file

### ISSUE THREAD

**Issue by sacsar** [bufbuild/rules_buf#22]
I'm finding that the `buf_lint_test` rule does not respect the config file.

To replicate, make the following change in `examples/single_module/buf.yaml`:
```
diff --git a/examples/single_module/buf.yaml b/examples/single_module/buf.yaml
index 1a51945..94fb192 100644
--- a/examples/single_module/buf.yaml
+++ b/examples/single_module/buf.yaml
@@ -4,4 +4,4 @@ breaking:
     - FILE
 lint:
   use:
-    - DEFAULT
+    - COMMENT_FIELD
```
Run `bazel test //foo/v1:foo_proto_lint`. The test passes. However, when you run from the command line (v1.5.0), linting fails (as expected):
```
buf lint --config buf.yaml --path  foo/v1/foo.proto
foo/v1/foo.proto:20:3:Field "id" should have a non-empty comment for documentation.
foo/v1/foo.proto:21:3:Field "name" should have a non-empty comment for documentation.
```

**Comment by srikrsna-buf** [comment]
Hey! Thank you for reporting this with steps to replicate. I can replicate this. 

This is a tough one! The rule does take the file into account, I can confirm that by adding the [UNARY_RPC](https://docs.buf.build/lint/rules#unary_rpc) lint category and the test fails if there is a streaming rpc. I suspect it has something to with how `proto_library` generates descriptors. I'll keep digging, just wanted to provide an update.

**Comment by jhump** [comment]
Is the `buf.yaml` file explicitly configured as an input to the rule? If not, this could have something to do with the filesystem "sandbox" bazel creates at build time, to provide inputs to the rule.

**Comment by sacsar** [comment]
I bet you're right. I will try it out and report back.

**Comment by sacsar** [comment]
There's a `config` parameter in `buf_lint_test` that gets passed down to `protoc_plugin_test` in buf/internal/plugin.bzl, but it doesn't actually specify the config parameter as an input.

**Comment by srikrsna-buf** [comment]
> There's a `config` parameter in `buf_lint_test` that gets passed down to `protoc_plugin_test` in buf/internal/plugin.bzl, but it doesn't actually specify the config parameter as an input.

We are passing the config see https://github.com/bufbuild/rules_buf/blob/1191ce869b0d067338c08f7388428d23d5dc3ce1/buf/internal/lint.bzl#L31

This could be related to #32 which was fixed with new `buf` version. Let me try to replicate this and see if it is a similar issue.

**Comment by sacsar** [comment]
I'll leave it to you to close the issue, but the config file appears to be working with `rules_buf` `0.2.0`
