### ISSUE TITLE
Support bzlmod

### ISSUE THREAD

**Issue by kyleconroy** [bufbuild/rules_buf#33]
I'm not sure if these rules support bzlmod. If they do, could you update the documentation with instructions on how to use it similar to [rules_js](https://github.com/aspect-build/rules_js/releases/tag/v1.13.0)?

**Comment by jtcarnes** [comment]
I'm also curious. My team is transitioning to using Bazel and it would be great to integrate buf with it. (for internal reasons, it's much easier to use bzlmods over the normal way)

**Comment by kyleconroy** [comment]
Checking in here. Any update on bzlmod support?

**Comment by DebkanchanSamadder** [comment]
Just migrating to bzlmod. Only dep left is this

**Comment by srikrsna-buf** [comment]
We can start using this repo with bzlmod with an override, or if you're not using gazelle can directly depend on the current version via the bzlmod registry.

Will create a release and update the registry soon.
