### ISSUE TITLE
feature request: buf_format_test rule or similar

### ISSUE THREAD

**Issue by sacsar** [bufbuild/rules_buf#54]
One of the big problems I'm using `rules_buf` to solve is ensuring that everyone is using the same version of `buf`, especially since the formatter behaviour has changed over time. At the moment, I just encourage people to use `brew` to install the cli and run `buf format` as a pre-commit hook, but we don't actually enforce formatting. Adding a rule to enforce formatting as well as linting would be nice.

If I ever get round to doing this myself, I'll send a PR.

**Comment by sacsar** [comment]
I discovered that https://github.com/aspect-build/rules_lint exists and supports buf, so this is somewhat redundant.

**Comment by chrispine** [comment]
Going to go ahead and close this, but feel free to re-open if needed. Thanks!
