### ISSUE TITLE
Use repository_ctx.os.name and repository_ctx.os.arch

### ISSUE THREAD

**Issue by kusaeva** [bufbuild/rules_buf#57]
Hi!
What do you think about starting using  repository_ctx.os.name and repository_ctx.os.arch [here](https://github.com/bufbuild/rules_buf/blob/main/buf/internal/toolchain.bzl#L86). 
The comment refers to already closed issue
We hase some problem with buf toolchains on apple m2 pro:
```
ToolchainResolution: Type @rules_buf//tools/protoc-gen-buf-lint:toolchain_type: execution platform @local_config_platform//:host: Rejected toolchain @rules_buf_toolchains//:protoc-gen-buf-lint_toolchain_impl; mismatching values: x86_64
```
Hope it helps

**Comment by srikrsna-buf** [comment]
Hey! That'd be great to use that, can you send a PR for that? Also it is odd because I've tested this on Apple silicon

**Comment by kusaeva** [comment]
I have two machines with m2 pro, one has a problem with toolchain, other - not, still can't figure out the difference (-__-)
