### ISSUE TITLE
protoc plugin does not respect ignores

### ISSUE THREAD

**Issue by SpencerC** [bufbuild/rules_buf#64]
Given a proto:
```proto
version: v1
lint:
  use:
    - DEFAULT
  allow_comment_ignores: true
  ignore:
    - IMPORT_USED
```
And a `buf.yaml`
```yaml
syntax = "proto3";

// buf:lint:ignore IMPORT_USED
import "unused.proto";
import "validate/validate.proto";
```

Running a `buf_lint_test` outputs:
```
--buf-plugin_out: file.proto:1:1:Import "unused.proto" is unused.
file.proto:1:1:Import "validate/validate.proto" is unused.
file.proto:1:1:Files must have a package defined.
unused.proto:1:1:Files must have a package defined.
```
It's definitely reading the `buf.yaml` file: `use: -RPC_REQUEST_STANDARD_NAME` causes all the errors to go away.

Reproducible example: https://github.com/SpencerC/rules_buf/commit/e38bd77ec5b3a8a87ebe88668e936502373c5421

Related: https://github.com/aspect-build/rules_lint/issues/222

**Comment by srikrsna-buf** [comment]
Hey! `proto_library` rules don't include the source code info by default, the comment gets stripped. There are two ways to solve this:
- Use `ignore_only` to skip a rule for specific files. More on this [here](https://buf.build/docs/configuration/v1/buf-yaml#ignore_only).
- Add the build flag `--experimental_proto_descriptor_sets_include_source_info`. More on this [here](https://github.com/bazelbuild/rules_proto/issues/56)

**Comment by SpencerC** [comment]
Thanks @srikrsna-buf. `--experimental_proto_descriptor_sets_include_source_info` makes `allow_comment_ignores` work. However, there still seems to be a problem with `ignore`. When adding that flag to the complete example above, the errors appear when the `buf:lint:ignore` comment is present, but not when it isn't.

**Comment by srikrsna-buf** [comment]
I think I see the issue, `ignore` is used to ignore files. `Except` is used to exclude rules: https://buf.build/docs/configuration/v1/buf-yaml#except
